# ---- Build (Node 22) ----
FROM node:22-alpine AS build
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
COPY .env.production .env

# Backend URL and other VITE_* provided at build-time if needed
ARG VITE_BACKEND_URL
ENV VITE_BACKEND_URL=${VITE_BACKEND_URL}

ARG VITE_CLERK_PUBLISHABLE_KEY
ENV VITE_CLERK_PUBLISHABLE_KEY=${VITE_CLERK_PUBLISHABLE_KEY}

ARG VITE_COMING_SOON_FLAG
ENV VITE_COMING_SOON_FLAG=${VITE_COMING_SOON_FLAG}

ARG VITE_DEFAULT_ADULT_PRICE
ENV VITE_DEFAULT_ADULT_PRICE=${VITE_DEFAULT_ADULT_PRICE}

ARG VITE_DEFAULT_CHILDREN_PRICE
ENV VITE_DEFAULT_CHILDREN_PRICE=${VITE_DEFAULT_CHILDREN_PRICE}

ARG VITE_MAX_EXCLUSIVE_PROMOS
ENV VITE_MAX_EXCLUSIVE_PROMOS=${VITE_MAX_EXCLUSIVE_PROMOS}

RUN npm run build

# ---- Serve (Nginx 1.28) ----
FROM nginx:1.28-alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]